lr: 3e-4
ent_coef: 0.05
clip_eps: 0.2
num_envs: 32
num_steps: 128
gamma: 1.0
gae_gamma: 0.95
num_minibatches: 4
num_ppo_epoch: 4
mag_coef: 0.2
mag_divergence_type: "kl"
num_inner_update: 1000
num_outer_update: 50

# Control Variate parameters
cv_enabled: false                 # Enable/disable CV variance reduction
cv_num_snapshot_steps: 128        # Steps for baseline gradient computation
cv_coefficient: 1.0               # CV correction strength (1.0 = full)
cv_is_clip: 10.0                  # Clip IS ratios to [1/clip, clip]